// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"github.com/cynt4k/router-dns-bridge/cmd/config"
	"github.com/cynt4k/router-dns-bridge/internal/router"
	"github.com/cynt4k/router-dns-bridge/internal/services"
	"github.com/cynt4k/router-dns-bridge/internal/services/powerdns"
	"github.com/cynt4k/router-dns-bridge/pkg/logger"
	"github.com/leandro-lugaresi/hub"
)

// Injectors from serve_wire.go:

func newServer(hub2 *hub.Hub, logger2 logger.Logger, config2 *config.Config) (*Server, error) {
	powerDNS, err := powerdns.NewService(hub2, config2, logger2)
	if err != nil {
		return nil, err
	}
	servicesServices := &services.Services{
		PowerDNS: powerDNS,
	}
	echo := router.New(hub2, config2, servicesServices, logger2)
	server := &Server{
		echo:   echo,
		logger: logger2,
		SS:     servicesServices,
		Hub:    hub2,
	}
	return server, nil
}
