// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package router

import (
	"github.com/cynt4k/router-dns-bridge/cmd/config"
	"github.com/cynt4k/router-dns-bridge/internal/router/v1"
	"github.com/cynt4k/router-dns-bridge/internal/services"
	"github.com/cynt4k/router-dns-bridge/pkg/logger"
	"github.com/leandro-lugaresi/hub"
)

// Injectors from router_wire.go:

func newRouter(hub2 *hub.Hub, ss *services.Services, config2 *config.Config, logger2 logger.Logger) *router {
	echo := newEcho(config2, logger2)
	powerDNS := ss.PowerDNS
	handlers := &v1.Handlers{
		PowerDNS: powerDNS,
	}
	routerRouter := &router{
		e:  echo,
		v1: handlers,
	}
	return routerRouter
}
